version: '3'
services:
  web1:
    build:
      context: .
      args:
        comd_var: cmatrix
    ports:
      - "4000:8080"
  web2:
    build:
      context: .
      args:
        comd_var: sl
    ports:
      - "5000:8080"
